name: techdivision/import-cli-simple

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
    
  run:
    name: Build ${{ matrix.operating-system }} > ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    services:
      magento:
        image: docker://techdivision/magento2-ce:2.3.5
        env:
          MAGENTO_BASE_URL: magento.test
        ports:
          - 80:80
          - 443:443
          - 3306:3306
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.3', '7.4' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo, pdo-mysql, zip, xdebug-2.9.8 

    - name: Validate Composer Files
      run: composer validate

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare Docker Container
      run: vendor/bin/robo prepare:docker magento.test ${{ job.services.magento.id }}

    - name: Update local DNS configuration
      run: sudo echo "127.0.0.1 magento.test" | sudo tee -a /etc/hosts

    - name: Run Acceptance Tests
      run: MAGENTO_INSTALL_DIR=/var/www/dist MAGENTO_CONTAINER_NAME=${{ job.services.magento.id }} vendor/bin/robo run:tests-acceptance

    - name: Run Integration Tests
      run: MAGENTO_CONTAINER_NAME=${{ job.services.magento.id }} vendor/bin/robo run:tests-integration

    - name: Run Build
      run: vendor/bin/robo build
      
    - name: Download Scrutinizer-CI Binary
      run: wget https://scrutinizer-ci.com/ocular.phar
    
    - name: Post Coverage Data to Scrutinizer-CI
      run: php ocular.phar code-coverage:upload --format=php-clover target/reports/unit/clover.xml
